# Generated by Django 5.0.3 on 2024-04-04 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_instagram_link',
            new_name='member_instagram_ID',
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 4, 19, 55, 13, 466980, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 4, 19, 55, 13, 466980, tzinfo=datetime.timezone.utc)),
        ),
    ]
