# Generated by Django 5.0.3 on 2024-04-09 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0004_club_alter_hero_join_date_alter_hero_update_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(default='/media/default.jpg', upload_to='about')),
                ('about_heading', models.CharField(default=None, max_length=64)),
                ('about_p1', models.TextField(max_length=500)),
                ('about_p2', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='hero',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 9, 8, 25, 40, 682954, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 9, 8, 25, 40, 682954, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 9, 8, 25, 40, 682954, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 9, 8, 25, 40, 682954, tzinfo=datetime.timezone.utc)),
        ),
    ]
