# Generated by Django 5.0.3 on 2024-04-10 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0006_students_alter_hero_join_date_alter_hero_update_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='Enter Name', max_length=50)),
                ('student_branch', models.CharField(default=None, max_length=100)),
                ('student_section', models.IntegerField(default=None, max_length=3)),
                ('student_admission_id', models.CharField(default=None, max_length=20)),
                ('student_phone', models.BigIntegerField(default=None, max_length=10)),
                ('student_club', models.CharField(default=None, max_length=50)),
                ('student_instagram_ID', models.CharField(default='https://www.instagram.com/', max_length=200)),
                ('student_linkedin_link', models.CharField(default='https://www.linkedin.com/feed/', max_length=200)),
                ('student_facebook_link', models.CharField(default='https://www.facebook.com/home.php', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='students',
        ),
        migrations.AlterField(
            model_name='hero',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 10, 29, 9, 736462, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 10, 29, 9, 736462, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 10, 29, 9, 734462, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 10, 29, 9, 734462, tzinfo=datetime.timezone.utc)),
        ),
    ]
