# Generated by Django 5.0.3 on 2024-04-10 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0008_students_delete_student_alter_hero_join_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 10, 34, 50, 987946, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 10, 34, 50, 987946, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 10, 34, 50, 985919, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 10, 34, 50, 985919, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_phone',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
