# Generated by Django 5.0.3 on 2024-04-10 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0010_alter_hero_join_date_alter_hero_update_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='hero',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 15, 24, 14, 863852, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 15, 24, 14, 863852, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 15, 24, 14, 862856, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 15, 24, 14, 862856, tzinfo=datetime.timezone.utc)),
        ),
    ]
