# Generated by Django 5.0.3 on 2024-04-10 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0012_alter_hero_join_date_alter_hero_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 17, 0, 51, 160685, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 17, 0, 51, 160685, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 17, 0, 51, 160685, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_instagram_ID',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_twitter_link',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 17, 0, 51, 160685, tzinfo=datetime.timezone.utc)),
        ),
    ]
