# Generated by Django 5.0.3 on 2024-04-10 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0013_alter_hero_join_date_alter_hero_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.ImageField(default='default.jpg', upload_to='student/images'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 17, 10, 43, 897675, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 17, 10, 43, 897675, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 17, 10, 43, 897675, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 17, 10, 43, 897675, tzinfo=datetime.timezone.utc)),
        ),
    ]
