# Generated by Django 5.0.3 on 2024-04-13 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0014_student_student_image_alter_hero_join_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(default=None, max_length=80)),
                ('event_date', models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 13, 9, 6, 32, 687312, tzinfo=datetime.timezone.utc))),
                ('event_para', models.TextField(max_length=1000)),
                ('event_image', models.ImageField(default='default.png', upload_to='event')),
                ('event_host_image', models.ImageField(default='default_user.png', upload_to='event/host')),
            ],
        ),
        migrations.AlterField(
            model_name='hero',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 9, 6, 32, 686309, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 9, 6, 32, 686309, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 9, 6, 32, 685310, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 9, 6, 32, 685310, tzinfo=datetime.timezone.utc)),
        ),
    ]
