# Generated by Django 5.0.3 on 2024-04-13 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0015_event_alter_hero_join_date_alter_hero_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_hoste_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 13, 13, 55, 3, 697328, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 13, 55, 3, 696336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 13, 55, 3, 696336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 13, 55, 3, 695321, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 13, 55, 3, 695321, tzinfo=datetime.timezone.utc)),
        ),
    ]
