# Generated by Django 5.0.3 on 2024-04-13 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0016_event_event_hoste_name_alter_event_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_course',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 13, 16, 48, 36, 908771, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 16, 48, 36, 907766, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 16, 48, 36, 907766, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 16, 48, 36, 907766, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 16, 48, 36, 907766, tzinfo=datetime.timezone.utc)),
        ),
    ]
