# Generated by Django 5.0.3 on 2024-04-13 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0017_member_member_course_alter_event_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_name', models.CharField(default=None, max_length=50)),
                ('registration_phone', models.CharField(default=None, max_length=50)),
                ('registration_email', models.CharField(default=None, max_length=50)),
                ('registration_course', models.CharField(default=None, max_length=50)),
                ('registration_admission_no', models.CharField(default=None, max_length=50)),
                ('registration_section', models.CharField(default=None, max_length=50)),
                ('registration_course_year', models.CharField(default=None, max_length=50)),
                ('registration_dob', models.CharField(default=None, max_length=50)),
                ('registration_skill', models.CharField(default=None, max_length=50)),
                ('registration_gender', models.CharField(default=None, max_length=50)),
                ('registration_profile', models.ImageField(upload_to=None)),
                ('registration_payment_image', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 13, 21, 55, 47, 448783, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 21, 55, 47, 448783, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 21, 55, 47, 448783, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 21, 55, 47, 447784, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 13, 21, 55, 47, 447784, tzinfo=datetime.timezone.utc)),
        ),
    ]
