# Generated by Django 5.0.3 on 2024-05-21 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0018_registration_alter_event_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 21, 10, 6, 1, 951716, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 5, 21, 10, 6, 1, 951716, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hero',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 5, 21, 10, 6, 1, 951716, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 5, 21, 10, 6, 1, 951716, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 5, 21, 10, 6, 1, 951716, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_name',
            field=models.CharField(max_length=50),
        ),
    ]
